name: Build
on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  Sonar-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'zulu'
          java-package: 'jdk+fx'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Sonar analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: ./gradlew jacocoTestReport sonar

  Build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: 'zulu'
          java-package: 'jdk+fx'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Gradle build
        run: ./gradlew build
